# Generated by Django 5.2.17 on 2026-10-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='list_item_complet_5e9f80_idx',
            old_name='list_item_complet_3f7a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='list_item_due_dat_f1b032_idx',
            old_name='list_item_due_dat_5b2e94_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='list_item_priorit_77b537_idx',
            old_name='list_item_priorit_a1d8f0_idx',
        ),
    ]
